const level1 = new Level(
    [
        new Chick('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
        new Chick('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
        new Chick('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
        new Chick('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
        new Chick('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
        new Chick('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
        new Chick('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
        new Chick('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
        new Chick('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
        new Chick('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
        new Chick('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
        new Chick('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
        new Boss(),
    ],
    [
        new Clouds('img/5_background/layers/4_clouds/1.png'),
        new Clouds('img/5_background/layers/4_clouds/2.png'),
    ],
    [
        new Background('img/5_background/layers/3_third_layer/1.png', 0, 0),
        new Background('img/5_background/layers/3_third_layer/2.png', 0, 720),
        new Background('img/5_background/layers/3_third_layer/1.png', 0, 1440),
        new Background('img/5_background/layers/3_third_layer/2.png', 0, 2160),
        new Background('img/5_background/layers/3_third_layer/1.png', 0, 2880),
        new Background('img/5_background/layers/3_third_layer/2.png', 0, 3600),
        new Background('img/5_background/layers/3_third_layer/1.png', 0, 4320),
        new Background('img/5_background/layers/3_third_layer/2.png', 0, 5040),
    ],
    [
        new BackGrnObj('img/5_background/layers/2_second_layer/1.png', 0, 0),
        new BackGrnObj('img/5_background/layers/2_second_layer/2.png', 0, 720),
        new BackGrnObj('img/5_background/layers/2_second_layer/1.png', 0, 1440),
        new BackGrnObj('img/5_background/layers/2_second_layer/2.png', 0, 2160),
        new BackGrnObj('img/5_background/layers/2_second_layer/1.png', 0, 2880),
        new BackGrnObj('img/5_background/layers/2_second_layer/2.png', 0, 3600),
        new BackGrnObj('img/5_background/layers/2_second_layer/1.png', 0, 4320),
        new BackGrnObj('img/5_background/layers/2_second_layer/2.png', 0, 5040),

        new BackGrnObj('img/5_background/layers/1_first_layer/1.png', 0, 0),
        new BackGrnObj('img/5_background/layers/1_first_layer/2.png', 0, 720),
        new BackGrnObj('img/5_background/layers/1_first_layer/1.png', 0, 1440),
        new BackGrnObj('img/5_background/layers/1_first_layer/2.png', 0, 2160),
        new BackGrnObj('img/5_background/layers/1_first_layer/1.png', 0, 2880),
        new BackGrnObj('img/5_background/layers/1_first_layer/2.png', 0, 3600),
        new BackGrnObj('img/5_background/layers/1_first_layer/1.png', 0, 4320),
        new BackGrnObj('img/5_background/layers/1_first_layer/2.png', 0, 5040),
    ],
    [
        new AmmoBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 360, 480),
        new AmmoBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 360, 990),
        new AmmoBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 360, 1800),
        new AmmoBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 360, 2400),
        new AmmoBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 360, 3800),
        new AmmoBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 360, 4800),
    ],
    [
        new Sky('img/5_background/layers/air.png',0, 0),
        new Sky('img/5_background/layers/air.png',0, 719),
        new Sky('img/5_background/layers/air.png',0, 1437),
        new Sky('img/5_background/layers/air.png',0, 2156),
        new Sky('img/5_background/layers/air.png',0, 2875),
        new Sky('img/5_background/layers/air.png',0, 3594),
        new Sky('img/5_background/layers/air.png',0, 4313),
        new Sky('img/5_background/layers/air.png',0, 5032),
    ],
)